#ifdef verify 
#undef verify 
#endif 
#ifdef check 
#undef check 
#endif 
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Protocol.proto
// Protobuf C++ Version: 6.33.4

#ifndef Protocol_2eproto_2epb_2eh
#define Protocol_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "Enum.pb.h"
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Protocol_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Protocol_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Protocol_2eproto;
}  // extern "C"
namespace Protocol {
class C_LoginPacket;
struct C_LoginPacketDefaultTypeInternal;
extern C_LoginPacketDefaultTypeInternal _C_LoginPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_LoginPacket_class_data_;
class C_SignUpPacket;
struct C_SignUpPacketDefaultTypeInternal;
extern C_SignUpPacketDefaultTypeInternal _C_SignUpPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull C_SignUpPacket_class_data_;
class S_ItemDataPacket;
struct S_ItemDataPacketDefaultTypeInternal;
extern S_ItemDataPacketDefaultTypeInternal _S_ItemDataPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_ItemDataPacket_class_data_;
class S_LoginFailPacket;
struct S_LoginFailPacketDefaultTypeInternal;
extern S_LoginFailPacketDefaultTypeInternal _S_LoginFailPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_LoginFailPacket_class_data_;
class S_LoginSuccessPacket;
struct S_LoginSuccessPacketDefaultTypeInternal;
extern S_LoginSuccessPacketDefaultTypeInternal _S_LoginSuccessPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_LoginSuccessPacket_class_data_;
class S_SignUpResultPacket;
struct S_SignUpResultPacketDefaultTypeInternal;
extern S_SignUpResultPacketDefaultTypeInternal _S_SignUpResultPacket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull S_SignUpResultPacket_class_data_;
}  // namespace Protocol
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace Protocol {

// ===================================================================


// -------------------------------------------------------------------

class S_SignUpResultPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_SignUpResultPacket) */ {
 public:
  inline S_SignUpResultPacket() : S_SignUpResultPacket(nullptr) {}
  ~S_SignUpResultPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_SignUpResultPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_SignUpResultPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_SignUpResultPacket(::google::protobuf::internal::ConstantInitialized);

  inline S_SignUpResultPacket(const S_SignUpResultPacket& from) : S_SignUpResultPacket(nullptr, from) {}
  inline S_SignUpResultPacket(S_SignUpResultPacket&& from) noexcept
      : S_SignUpResultPacket(nullptr, ::std::move(from)) {}
  inline S_SignUpResultPacket& operator=(const S_SignUpResultPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_SignUpResultPacket& operator=(S_SignUpResultPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_SignUpResultPacket& default_instance() {
    return *reinterpret_cast<const S_SignUpResultPacket*>(
        &_S_SignUpResultPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(S_SignUpResultPacket& a, S_SignUpResultPacket& b) { a.Swap(&b); }
  inline void Swap(S_SignUpResultPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_SignUpResultPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_SignUpResultPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_SignUpResultPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_SignUpResultPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_SignUpResultPacket& from) { S_SignUpResultPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_SignUpResultPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_SignUpResultPacket"; }

  explicit S_SignUpResultPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_SignUpResultPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_SignUpResultPacket& from);
  S_SignUpResultPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_SignUpResultPacket&& from) noexcept
      : S_SignUpResultPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSuccessFieldNumber = 1,
  };
  // bool success = 1;
  void clear_success() ;
  bool success() const;
  void set_success(bool value);

  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_SignUpResultPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_SignUpResultPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_SignUpResultPacket_class_data_;
// -------------------------------------------------------------------

class S_LoginSuccessPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_LoginSuccessPacket) */ {
 public:
  inline S_LoginSuccessPacket() : S_LoginSuccessPacket(nullptr) {}
  ~S_LoginSuccessPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_LoginSuccessPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_LoginSuccessPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_LoginSuccessPacket(::google::protobuf::internal::ConstantInitialized);

  inline S_LoginSuccessPacket(const S_LoginSuccessPacket& from) : S_LoginSuccessPacket(nullptr, from) {}
  inline S_LoginSuccessPacket(S_LoginSuccessPacket&& from) noexcept
      : S_LoginSuccessPacket(nullptr, ::std::move(from)) {}
  inline S_LoginSuccessPacket& operator=(const S_LoginSuccessPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LoginSuccessPacket& operator=(S_LoginSuccessPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LoginSuccessPacket& default_instance() {
    return *reinterpret_cast<const S_LoginSuccessPacket*>(
        &_S_LoginSuccessPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(S_LoginSuccessPacket& a, S_LoginSuccessPacket& b) { a.Swap(&b); }
  inline void Swap(S_LoginSuccessPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LoginSuccessPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LoginSuccessPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_LoginSuccessPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_LoginSuccessPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_LoginSuccessPacket& from) { S_LoginSuccessPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_LoginSuccessPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_LoginSuccessPacket"; }

  explicit S_LoginSuccessPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_LoginSuccessPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_LoginSuccessPacket& from);
  S_LoginSuccessPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_LoginSuccessPacket&& from) noexcept
      : S_LoginSuccessPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerClassFieldNumber = 1,
    kGoldFieldNumber = 2,
    kExpFieldNumber = 3,
    kHpFieldNumber = 4,
    kPlayerIdFieldNumber = 6,
  };
  // .Protocol.ClassType playerClass = 1;
  void clear_playerclass() ;
  ::Protocol::ClassType playerclass() const;
  void set_playerclass(::Protocol::ClassType value);

  private:
  ::Protocol::ClassType _internal_playerclass() const;
  void _internal_set_playerclass(::Protocol::ClassType value);

  public:
  // int32 gold = 2;
  void clear_gold() ;
  ::int32_t gold() const;
  void set_gold(::int32_t value);

  private:
  ::int32_t _internal_gold() const;
  void _internal_set_gold(::int32_t value);

  public:
  // int32 exp = 3;
  void clear_exp() ;
  ::int32_t exp() const;
  void set_exp(::int32_t value);

  private:
  ::int32_t _internal_exp() const;
  void _internal_set_exp(::int32_t value);

  public:
  // int32 hp = 4;
  void clear_hp() ;
  ::int32_t hp() const;
  void set_hp(::int32_t value);

  private:
  ::int32_t _internal_hp() const;
  void _internal_set_hp(::int32_t value);

  public:
  // uint32 playerId = 6;
  void clear_playerid() ;
  ::uint32_t playerid() const;
  void set_playerid(::uint32_t value);

  private:
  ::uint32_t _internal_playerid() const;
  void _internal_set_playerid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.S_LoginSuccessPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_LoginSuccessPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int playerclass_;
    ::int32_t gold_;
    ::int32_t exp_;
    ::int32_t hp_;
    ::uint32_t playerid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_LoginSuccessPacket_class_data_;
// -------------------------------------------------------------------

class S_LoginFailPacket final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:Protocol.S_LoginFailPacket) */ {
 public:
  inline S_LoginFailPacket() : S_LoginFailPacket(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_LoginFailPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_LoginFailPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_LoginFailPacket(::google::protobuf::internal::ConstantInitialized);

  inline S_LoginFailPacket(const S_LoginFailPacket& from) : S_LoginFailPacket(nullptr, from) {}
  inline S_LoginFailPacket(S_LoginFailPacket&& from) noexcept
      : S_LoginFailPacket(nullptr, ::std::move(from)) {}
  inline S_LoginFailPacket& operator=(const S_LoginFailPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LoginFailPacket& operator=(S_LoginFailPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LoginFailPacket& default_instance() {
    return *reinterpret_cast<const S_LoginFailPacket*>(
        &_S_LoginFailPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(S_LoginFailPacket& a, S_LoginFailPacket& b) { a.Swap(&b); }
  inline void Swap(S_LoginFailPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LoginFailPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LoginFailPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<S_LoginFailPacket>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const S_LoginFailPacket& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const S_LoginFailPacket& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_LoginFailPacket"; }

  explicit S_LoginFailPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_LoginFailPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_LoginFailPacket& from);
  S_LoginFailPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_LoginFailPacket&& from) noexcept
      : S_LoginFailPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:Protocol.S_LoginFailPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_LoginFailPacket_class_data_;
// -------------------------------------------------------------------

class C_SignUpPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_SignUpPacket) */ {
 public:
  inline C_SignUpPacket() : C_SignUpPacket(nullptr) {}
  ~C_SignUpPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_SignUpPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_SignUpPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_SignUpPacket(::google::protobuf::internal::ConstantInitialized);

  inline C_SignUpPacket(const C_SignUpPacket& from) : C_SignUpPacket(nullptr, from) {}
  inline C_SignUpPacket(C_SignUpPacket&& from) noexcept
      : C_SignUpPacket(nullptr, ::std::move(from)) {}
  inline C_SignUpPacket& operator=(const C_SignUpPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_SignUpPacket& operator=(C_SignUpPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_SignUpPacket& default_instance() {
    return *reinterpret_cast<const C_SignUpPacket*>(
        &_C_SignUpPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(C_SignUpPacket& a, C_SignUpPacket& b) { a.Swap(&b); }
  inline void Swap(C_SignUpPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_SignUpPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_SignUpPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_SignUpPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_SignUpPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_SignUpPacket& from) { C_SignUpPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_SignUpPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_SignUpPacket"; }

  explicit C_SignUpPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_SignUpPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_SignUpPacket& from);
  C_SignUpPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_SignUpPacket&& from) noexcept
      : C_SignUpPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kClassTypeFieldNumber = 3,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string password = 2;
  void clear_password() ;
  const ::std::string& password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_password();
  void set_allocated_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_password();

  public:
  // .Protocol.ClassType classType = 3;
  void clear_classtype() ;
  ::Protocol::ClassType classtype() const;
  void set_classtype(::Protocol::ClassType value);

  private:
  ::Protocol::ClassType _internal_classtype() const;
  void _internal_set_classtype(::Protocol::ClassType value);

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_SignUpPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 42,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_SignUpPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    int classtype_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_SignUpPacket_class_data_;
// -------------------------------------------------------------------

class C_LoginPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.C_LoginPacket) */ {
 public:
  inline C_LoginPacket() : C_LoginPacket(nullptr) {}
  ~C_LoginPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(C_LoginPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(C_LoginPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR C_LoginPacket(::google::protobuf::internal::ConstantInitialized);

  inline C_LoginPacket(const C_LoginPacket& from) : C_LoginPacket(nullptr, from) {}
  inline C_LoginPacket(C_LoginPacket&& from) noexcept
      : C_LoginPacket(nullptr, ::std::move(from)) {}
  inline C_LoginPacket& operator=(const C_LoginPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LoginPacket& operator=(C_LoginPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LoginPacket& default_instance() {
    return *reinterpret_cast<const C_LoginPacket*>(
        &_C_LoginPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(C_LoginPacket& a, C_LoginPacket& b) { a.Swap(&b); }
  inline void Swap(C_LoginPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LoginPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LoginPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<C_LoginPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const C_LoginPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const C_LoginPacket& from) { C_LoginPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(C_LoginPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.C_LoginPacket"; }

  explicit C_LoginPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  C_LoginPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const C_LoginPacket& from);
  C_LoginPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, C_LoginPacket&& from) noexcept
      : C_LoginPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kPasswordFieldNumber = 2,
  };
  // string id = 1;
  void clear_id() ;
  const ::std::string& id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_id();
  void set_allocated_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_id();

  public:
  // string password = 2;
  void clear_password() ;
  const ::std::string& password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_password();
  void set_allocated_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_password();

  public:
  // @@protoc_insertion_point(class_scope:Protocol.C_LoginPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 41,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const C_LoginPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr id_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull C_LoginPacket_class_data_;
// -------------------------------------------------------------------

class S_ItemDataPacket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Protocol.S_ItemDataPacket) */ {
 public:
  inline S_ItemDataPacket() : S_ItemDataPacket(nullptr) {}
  ~S_ItemDataPacket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(S_ItemDataPacket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(S_ItemDataPacket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR S_ItemDataPacket(::google::protobuf::internal::ConstantInitialized);

  inline S_ItemDataPacket(const S_ItemDataPacket& from) : S_ItemDataPacket(nullptr, from) {}
  inline S_ItemDataPacket(S_ItemDataPacket&& from) noexcept
      : S_ItemDataPacket(nullptr, ::std::move(from)) {}
  inline S_ItemDataPacket& operator=(const S_ItemDataPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_ItemDataPacket& operator=(S_ItemDataPacket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_ItemDataPacket& default_instance() {
    return *reinterpret_cast<const S_ItemDataPacket*>(
        &_S_ItemDataPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(S_ItemDataPacket& a, S_ItemDataPacket& b) { a.Swap(&b); }
  inline void Swap(S_ItemDataPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_ItemDataPacket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_ItemDataPacket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<S_ItemDataPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const S_ItemDataPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const S_ItemDataPacket& from) { S_ItemDataPacket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(S_ItemDataPacket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Protocol.S_ItemDataPacket"; }

  explicit S_ItemDataPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  S_ItemDataPacket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const S_ItemDataPacket& from);
  S_ItemDataPacket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, S_ItemDataPacket&& from) noexcept
      : S_ItemDataPacket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerItemsFieldNumber = 1,
  };
  // repeated .Protocol.ItemData playerItems = 1;
  int playeritems_size() const;
  private:
  int _internal_playeritems_size() const;

  public:
  void clear_playeritems() ;
  ::Protocol::ItemData* PROTOBUF_NONNULL mutable_playeritems(int index);
  ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>* PROTOBUF_NONNULL mutable_playeritems();

  private:
  const ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>& _internal_playeritems() const;
  ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>* PROTOBUF_NONNULL _internal_mutable_playeritems();
  public:
  const ::Protocol::ItemData& playeritems(int index) const;
  ::Protocol::ItemData* PROTOBUF_NONNULL add_playeritems();
  const ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>& playeritems() const;
  // @@protoc_insertion_point(class_scope:Protocol.S_ItemDataPacket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const S_ItemDataPacket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Protocol::ItemData > playeritems_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Protocol_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull S_ItemDataPacket_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// C_SignUpPacket

// string id = 1;
inline void C_SignUpPacket::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& C_SignUpPacket::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_SignUpPacket.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_SignUpPacket::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_SignUpPacket.id)
}
inline ::std::string* PROTOBUF_NONNULL C_SignUpPacket::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_SignUpPacket.id)
  return _s;
}
inline const ::std::string& C_SignUpPacket::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void C_SignUpPacket::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_SignUpPacket::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_SignUpPacket::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_SignUpPacket.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void C_SignUpPacket::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_SignUpPacket.id)
}

// string password = 2;
inline void C_SignUpPacket::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& C_SignUpPacket::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_SignUpPacket.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_SignUpPacket::set_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_SignUpPacket.password)
}
inline ::std::string* PROTOBUF_NONNULL C_SignUpPacket::mutable_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.C_SignUpPacket.password)
  return _s;
}
inline const ::std::string& C_SignUpPacket::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void C_SignUpPacket::_internal_set_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_SignUpPacket::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_SignUpPacket::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_SignUpPacket.password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.password_.Set("", GetArena());
  }
  return released;
}
inline void C_SignUpPacket::set_allocated_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_SignUpPacket.password)
}

// .Protocol.ClassType classType = 3;
inline void C_SignUpPacket::clear_classtype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classtype_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::Protocol::ClassType C_SignUpPacket::classtype() const {
  // @@protoc_insertion_point(field_get:Protocol.C_SignUpPacket.classType)
  return _internal_classtype();
}
inline void C_SignUpPacket::set_classtype(::Protocol::ClassType value) {
  _internal_set_classtype(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.C_SignUpPacket.classType)
}
inline ::Protocol::ClassType C_SignUpPacket::_internal_classtype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::ClassType>(_impl_.classtype_);
}
inline void C_SignUpPacket::_internal_set_classtype(::Protocol::ClassType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.classtype_ = value;
}

// -------------------------------------------------------------------

// S_SignUpResultPacket

// bool success = 1;
inline void S_SignUpResultPacket::clear_success() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline bool S_SignUpResultPacket::success() const {
  // @@protoc_insertion_point(field_get:Protocol.S_SignUpResultPacket.success)
  return _internal_success();
}
inline void S_SignUpResultPacket::set_success(bool value) {
  _internal_set_success(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.S_SignUpResultPacket.success)
}
inline bool S_SignUpResultPacket::_internal_success() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.success_;
}
inline void S_SignUpResultPacket::_internal_set_success(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.success_ = value;
}

// -------------------------------------------------------------------

// C_LoginPacket

// string id = 1;
inline void C_LoginPacket::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& C_LoginPacket::id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LoginPacket.id)
  return _internal_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_LoginPacket::set_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LoginPacket.id)
}
inline ::std::string* PROTOBUF_NONNULL C_LoginPacket::mutable_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_id();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LoginPacket.id)
  return _s;
}
inline const ::std::string& C_LoginPacket::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_.Get();
}
inline void C_LoginPacket::_internal_set_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_LoginPacket::_internal_mutable_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_LoginPacket::release_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LoginPacket.id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.id_.Set("", GetArena());
  }
  return released;
}
inline void C_LoginPacket::set_allocated_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.id_.IsDefault()) {
    _impl_.id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LoginPacket.id)
}

// string password = 2;
inline void C_LoginPacket::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& C_LoginPacket::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.C_LoginPacket.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void C_LoginPacket::set_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.password_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Protocol.C_LoginPacket.password)
}
inline ::std::string* PROTOBUF_NONNULL C_LoginPacket::mutable_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:Protocol.C_LoginPacket.password)
  return _s;
}
inline const ::std::string& C_LoginPacket::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void C_LoginPacket::_internal_set_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL C_LoginPacket::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE C_LoginPacket::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Protocol.C_LoginPacket.password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.password_.Set("", GetArena());
  }
  return released;
}
inline void C_LoginPacket::set_allocated_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Protocol.C_LoginPacket.password)
}

// -------------------------------------------------------------------

// S_LoginFailPacket

// -------------------------------------------------------------------

// S_LoginSuccessPacket

// .Protocol.ClassType playerClass = 1;
inline void S_LoginSuccessPacket::clear_playerclass() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerclass_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::Protocol::ClassType S_LoginSuccessPacket::playerclass() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginSuccessPacket.playerClass)
  return _internal_playerclass();
}
inline void S_LoginSuccessPacket::set_playerclass(::Protocol::ClassType value) {
  _internal_set_playerclass(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginSuccessPacket.playerClass)
}
inline ::Protocol::ClassType S_LoginSuccessPacket::_internal_playerclass() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::Protocol::ClassType>(_impl_.playerclass_);
}
inline void S_LoginSuccessPacket::_internal_set_playerclass(::Protocol::ClassType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerclass_ = value;
}

// int32 gold = 2;
inline void S_LoginSuccessPacket::clear_gold() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gold_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t S_LoginSuccessPacket::gold() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginSuccessPacket.gold)
  return _internal_gold();
}
inline void S_LoginSuccessPacket::set_gold(::int32_t value) {
  _internal_set_gold(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginSuccessPacket.gold)
}
inline ::int32_t S_LoginSuccessPacket::_internal_gold() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gold_;
}
inline void S_LoginSuccessPacket::_internal_set_gold(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gold_ = value;
}

// int32 exp = 3;
inline void S_LoginSuccessPacket::clear_exp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t S_LoginSuccessPacket::exp() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginSuccessPacket.exp)
  return _internal_exp();
}
inline void S_LoginSuccessPacket::set_exp(::int32_t value) {
  _internal_set_exp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginSuccessPacket.exp)
}
inline ::int32_t S_LoginSuccessPacket::_internal_exp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.exp_;
}
inline void S_LoginSuccessPacket::_internal_set_exp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.exp_ = value;
}

// int32 hp = 4;
inline void S_LoginSuccessPacket::clear_hp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t S_LoginSuccessPacket::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginSuccessPacket.hp)
  return _internal_hp();
}
inline void S_LoginSuccessPacket::set_hp(::int32_t value) {
  _internal_set_hp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginSuccessPacket.hp)
}
inline ::int32_t S_LoginSuccessPacket::_internal_hp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.hp_;
}
inline void S_LoginSuccessPacket::_internal_set_hp(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.hp_ = value;
}

// uint32 playerId = 6;
inline void S_LoginSuccessPacket::clear_playerid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t S_LoginSuccessPacket::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_LoginSuccessPacket.playerId)
  return _internal_playerid();
}
inline void S_LoginSuccessPacket::set_playerid(::uint32_t value) {
  _internal_set_playerid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Protocol.S_LoginSuccessPacket.playerId)
}
inline ::uint32_t S_LoginSuccessPacket::_internal_playerid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playerid_;
}
inline void S_LoginSuccessPacket::_internal_set_playerid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.playerid_ = value;
}

// -------------------------------------------------------------------

// S_ItemDataPacket

// repeated .Protocol.ItemData playerItems = 1;
inline int S_ItemDataPacket::_internal_playeritems_size() const {
  return _internal_playeritems().size();
}
inline int S_ItemDataPacket::playeritems_size() const {
  return _internal_playeritems_size();
}
inline ::Protocol::ItemData* PROTOBUF_NONNULL S_ItemDataPacket::mutable_playeritems(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:Protocol.S_ItemDataPacket.playerItems)
  return _internal_mutable_playeritems()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>* PROTOBUF_NONNULL S_ItemDataPacket::mutable_playeritems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:Protocol.S_ItemDataPacket.playerItems)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_playeritems();
}
inline const ::Protocol::ItemData& S_ItemDataPacket::playeritems(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Protocol.S_ItemDataPacket.playerItems)
  return _internal_playeritems().Get(index);
}
inline ::Protocol::ItemData* PROTOBUF_NONNULL S_ItemDataPacket::add_playeritems()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Protocol::ItemData* _add =
      _internal_mutable_playeritems()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:Protocol.S_ItemDataPacket.playerItems)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>& S_ItemDataPacket::playeritems() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Protocol.S_ItemDataPacket.playerItems)
  return _internal_playeritems();
}
inline const ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>&
S_ItemDataPacket::_internal_playeritems() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.playeritems_;
}
inline ::google::protobuf::RepeatedPtrField<::Protocol::ItemData>* PROTOBUF_NONNULL
S_ItemDataPacket::_internal_mutable_playeritems() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.playeritems_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Protocol_2eproto_2epb_2eh
