#ifdef verify 
#undef verify 
#endif 
#ifdef check 
#undef check 
#endif 
#undef PROTOBUF_USE_DLLS 
#define PROTOBUF_USE_DLLS 0 
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class ItemData;
struct ItemDataDefaultTypeInternal;
extern ItemDataDefaultTypeInternal _ItemData_default_instance_;
class PlayerInfo;
struct PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class PlayerState;
struct PlayerStateDefaultTypeInternal;
extern PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
class Rotator3;
struct Rotator3DefaultTypeInternal;
extern Rotator3DefaultTypeInternal _Rotator3_default_instance_;
class Vector3;
struct Vector3DefaultTypeInternal;
extern Vector3DefaultTypeInternal _Vector3_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ItemData* Arena::CreateMaybeMessage<::Protocol::ItemData>(Arena*);
template<> ::Protocol::PlayerInfo* Arena::CreateMaybeMessage<::Protocol::PlayerInfo>(Arena*);
template<> ::Protocol::PlayerState* Arena::CreateMaybeMessage<::Protocol::PlayerState>(Arena*);
template<> ::Protocol::Rotator3* Arena::CreateMaybeMessage<::Protocol::Rotator3>(Arena*);
template<> ::Protocol::Vector3* Arena::CreateMaybeMessage<::Protocol::Vector3>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class ItemData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ItemData) */ {
 public:
  inline ItemData() : ItemData(nullptr) {}
  ~ItemData() override;
  explicit PROTOBUF_CONSTEXPR ItemData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ItemData(const ItemData& from);
  ItemData(ItemData&& from) noexcept
    : ItemData() {
    *this = ::std::move(from);
  }

  inline ItemData& operator=(const ItemData& from) {
    CopyFrom(from);
    return *this;
  }
  inline ItemData& operator=(ItemData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ItemData& default_instance() {
    return *internal_default_instance();
  }
  static inline const ItemData* internal_default_instance() {
    return reinterpret_cast<const ItemData*>(
               &_ItemData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ItemData& a, ItemData& b) {
    a.Swap(&b);
  }
  inline void Swap(ItemData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ItemData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ItemData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ItemData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ItemData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ItemData& from) {
    ItemData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ItemData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ItemData";
  }
  protected:
  explicit ItemData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kItemInstancedIdFieldNumber = 1,
    kItemTemplateIdFieldNumber = 2,
    kSlotIndexFieldNumber = 3,
    kCountFieldNumber = 4,
  };
  // int32 itemInstancedId = 1;
  void clear_iteminstancedid();
  int32_t iteminstancedid() const;
  void set_iteminstancedid(int32_t value);
  private:
  int32_t _internal_iteminstancedid() const;
  void _internal_set_iteminstancedid(int32_t value);
  public:

  // int32 itemTemplateId = 2;
  void clear_itemtemplateid();
  int32_t itemtemplateid() const;
  void set_itemtemplateid(int32_t value);
  private:
  int32_t _internal_itemtemplateid() const;
  void _internal_set_itemtemplateid(int32_t value);
  public:

  // int32 slotIndex = 3;
  void clear_slotindex();
  int32_t slotindex() const;
  void set_slotindex(int32_t value);
  private:
  int32_t _internal_slotindex() const;
  void _internal_set_slotindex(int32_t value);
  public:

  // int32 count = 4;
  void clear_count();
  int32_t count() const;
  void set_count(int32_t value);
  private:
  int32_t _internal_count() const;
  void _internal_set_count(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ItemData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t iteminstancedid_;
    int32_t itemtemplateid_;
    int32_t slotindex_;
    int32_t count_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Vector3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Vector3) */ {
 public:
  inline Vector3() : Vector3(nullptr) {}
  ~Vector3() override;
  explicit PROTOBUF_CONSTEXPR Vector3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3(const Vector3& from);
  Vector3(Vector3&& from) noexcept
    : Vector3() {
    *this = ::std::move(from);
  }

  inline Vector3& operator=(const Vector3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3& operator=(Vector3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3* internal_default_instance() {
    return reinterpret_cast<const Vector3*>(
               &_Vector3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Vector3& a, Vector3& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector3& from) {
    Vector3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Vector3";
  }
  protected:
  explicit Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Vector3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class Rotator3 final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.Rotator3) */ {
 public:
  inline Rotator3() : Rotator3(nullptr) {}
  ~Rotator3() override;
  explicit PROTOBUF_CONSTEXPR Rotator3(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Rotator3(const Rotator3& from);
  Rotator3(Rotator3&& from) noexcept
    : Rotator3() {
    *this = ::std::move(from);
  }

  inline Rotator3& operator=(const Rotator3& from) {
    CopyFrom(from);
    return *this;
  }
  inline Rotator3& operator=(Rotator3&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Rotator3& default_instance() {
    return *internal_default_instance();
  }
  static inline const Rotator3* internal_default_instance() {
    return reinterpret_cast<const Rotator3*>(
               &_Rotator3_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Rotator3& a, Rotator3& b) {
    a.Swap(&b);
  }
  inline void Swap(Rotator3* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Rotator3* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Rotator3* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Rotator3>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Rotator3& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Rotator3& from) {
    Rotator3::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Rotator3* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.Rotator3";
  }
  protected:
  explicit Rotator3(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPitchFieldNumber = 1,
    kRollFieldNumber = 2,
    kYawFieldNumber = 3,
  };
  // float pitch = 1;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float roll = 2;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float yaw = 3;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.Rotator3)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float pitch_;
    float roll_;
    float yaw_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class PlayerInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerInfo) */ {
 public:
  inline PlayerInfo() : PlayerInfo(nullptr) {}
  ~PlayerInfo() override;
  explicit PROTOBUF_CONSTEXPR PlayerInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerInfo(const PlayerInfo& from);
  PlayerInfo(PlayerInfo&& from) noexcept
    : PlayerInfo() {
    *this = ::std::move(from);
  }

  inline PlayerInfo& operator=(const PlayerInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInfo& operator=(PlayerInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInfo* internal_default_instance() {
    return reinterpret_cast<const PlayerInfo*>(
               &_PlayerInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PlayerInfo& a, PlayerInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerInfo& from) {
    PlayerInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerInfo";
  }
  protected:
  explicit PlayerInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerIdFieldNumber = 1,
    kPlayerClassFieldNumber = 2,
  };
  // uint64 playerId = 1;
  void clear_playerid();
  uint64_t playerid() const;
  void set_playerid(uint64_t value);
  private:
  uint64_t _internal_playerid() const;
  void _internal_set_playerid(uint64_t value);
  public:

  // .Protocol.ClassType playerClass = 2;
  void clear_playerclass();
  ::Protocol::ClassType playerclass() const;
  void set_playerclass(::Protocol::ClassType value);
  private:
  ::Protocol::ClassType _internal_playerclass() const;
  void _internal_set_playerclass(::Protocol::ClassType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t playerid_;
    int playerclass_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class PlayerState final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.PlayerState) */ {
 public:
  inline PlayerState() : PlayerState(nullptr) {}
  ~PlayerState() override;
  explicit PROTOBUF_CONSTEXPR PlayerState(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerState(const PlayerState& from);
  PlayerState(PlayerState&& from) noexcept
    : PlayerState() {
    *this = ::std::move(from);
  }

  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerState& operator=(PlayerState&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerState& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerState* internal_default_instance() {
    return reinterpret_cast<const PlayerState*>(
               &_PlayerState_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(PlayerState& a, PlayerState& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerState* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerState* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerState* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerState>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerState& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerState& from) {
    PlayerState::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerState* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.PlayerState";
  }
  protected:
  explicit PlayerState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPlayerLocationFieldNumber = 3,
    kPlayerRotationFieldNumber = 4,
    kPlayerIdFieldNumber = 1,
    kPlayerClassFieldNumber = 2,
  };
  // .Protocol.Vector3 playerLocation = 3;
  bool has_playerlocation() const;
  private:
  bool _internal_has_playerlocation() const;
  public:
  void clear_playerlocation();
  const ::Protocol::Vector3& playerlocation() const;
  PROTOBUF_NODISCARD ::Protocol::Vector3* release_playerlocation();
  ::Protocol::Vector3* mutable_playerlocation();
  void set_allocated_playerlocation(::Protocol::Vector3* playerlocation);
  private:
  const ::Protocol::Vector3& _internal_playerlocation() const;
  ::Protocol::Vector3* _internal_mutable_playerlocation();
  public:
  void unsafe_arena_set_allocated_playerlocation(
      ::Protocol::Vector3* playerlocation);
  ::Protocol::Vector3* unsafe_arena_release_playerlocation();

  // .Protocol.Rotator3 playerRotation = 4;
  bool has_playerrotation() const;
  private:
  bool _internal_has_playerrotation() const;
  public:
  void clear_playerrotation();
  const ::Protocol::Rotator3& playerrotation() const;
  PROTOBUF_NODISCARD ::Protocol::Rotator3* release_playerrotation();
  ::Protocol::Rotator3* mutable_playerrotation();
  void set_allocated_playerrotation(::Protocol::Rotator3* playerrotation);
  private:
  const ::Protocol::Rotator3& _internal_playerrotation() const;
  ::Protocol::Rotator3* _internal_mutable_playerrotation();
  public:
  void unsafe_arena_set_allocated_playerrotation(
      ::Protocol::Rotator3* playerrotation);
  ::Protocol::Rotator3* unsafe_arena_release_playerrotation();

  // uint64 playerId = 1;
  void clear_playerid();
  uint64_t playerid() const;
  void set_playerid(uint64_t value);
  private:
  uint64_t _internal_playerid() const;
  void _internal_set_playerid(uint64_t value);
  public:

  // .Protocol.ClassType playerClass = 2;
  void clear_playerclass();
  ::Protocol::ClassType playerclass() const;
  void set_playerclass(::Protocol::ClassType value);
  private:
  ::Protocol::ClassType _internal_playerclass() const;
  void _internal_set_playerclass(::Protocol::ClassType value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.PlayerState)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::Protocol::Vector3* playerlocation_;
    ::Protocol::Rotator3* playerrotation_;
    uint64_t playerid_;
    int playerclass_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ItemData

// int32 itemInstancedId = 1;
inline void ItemData::clear_iteminstancedid() {
  _impl_.iteminstancedid_ = 0;
}
inline int32_t ItemData::_internal_iteminstancedid() const {
  return _impl_.iteminstancedid_;
}
inline int32_t ItemData::iteminstancedid() const {
  // @@protoc_insertion_point(field_get:Protocol.ItemData.itemInstancedId)
  return _internal_iteminstancedid();
}
inline void ItemData::_internal_set_iteminstancedid(int32_t value) {
  
  _impl_.iteminstancedid_ = value;
}
inline void ItemData::set_iteminstancedid(int32_t value) {
  _internal_set_iteminstancedid(value);
  // @@protoc_insertion_point(field_set:Protocol.ItemData.itemInstancedId)
}

// int32 itemTemplateId = 2;
inline void ItemData::clear_itemtemplateid() {
  _impl_.itemtemplateid_ = 0;
}
inline int32_t ItemData::_internal_itemtemplateid() const {
  return _impl_.itemtemplateid_;
}
inline int32_t ItemData::itemtemplateid() const {
  // @@protoc_insertion_point(field_get:Protocol.ItemData.itemTemplateId)
  return _internal_itemtemplateid();
}
inline void ItemData::_internal_set_itemtemplateid(int32_t value) {
  
  _impl_.itemtemplateid_ = value;
}
inline void ItemData::set_itemtemplateid(int32_t value) {
  _internal_set_itemtemplateid(value);
  // @@protoc_insertion_point(field_set:Protocol.ItemData.itemTemplateId)
}

// int32 slotIndex = 3;
inline void ItemData::clear_slotindex() {
  _impl_.slotindex_ = 0;
}
inline int32_t ItemData::_internal_slotindex() const {
  return _impl_.slotindex_;
}
inline int32_t ItemData::slotindex() const {
  // @@protoc_insertion_point(field_get:Protocol.ItemData.slotIndex)
  return _internal_slotindex();
}
inline void ItemData::_internal_set_slotindex(int32_t value) {
  
  _impl_.slotindex_ = value;
}
inline void ItemData::set_slotindex(int32_t value) {
  _internal_set_slotindex(value);
  // @@protoc_insertion_point(field_set:Protocol.ItemData.slotIndex)
}

// int32 count = 4;
inline void ItemData::clear_count() {
  _impl_.count_ = 0;
}
inline int32_t ItemData::_internal_count() const {
  return _impl_.count_;
}
inline int32_t ItemData::count() const {
  // @@protoc_insertion_point(field_get:Protocol.ItemData.count)
  return _internal_count();
}
inline void ItemData::_internal_set_count(int32_t value) {
  
  _impl_.count_ = value;
}
inline void ItemData::set_count(int32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:Protocol.ItemData.count)
}

// -------------------------------------------------------------------

// Vector3

// float x = 1;
inline void Vector3::clear_x() {
  _impl_.x_ = 0;
}
inline float Vector3::_internal_x() const {
  return _impl_.x_;
}
inline float Vector3::x() const {
  // @@protoc_insertion_point(field_get:Protocol.Vector3.x)
  return _internal_x();
}
inline void Vector3::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Vector3::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Protocol.Vector3.x)
}

// float y = 2;
inline void Vector3::clear_y() {
  _impl_.y_ = 0;
}
inline float Vector3::_internal_y() const {
  return _impl_.y_;
}
inline float Vector3::y() const {
  // @@protoc_insertion_point(field_get:Protocol.Vector3.y)
  return _internal_y();
}
inline void Vector3::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Vector3::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Protocol.Vector3.y)
}

// float z = 3;
inline void Vector3::clear_z() {
  _impl_.z_ = 0;
}
inline float Vector3::_internal_z() const {
  return _impl_.z_;
}
inline float Vector3::z() const {
  // @@protoc_insertion_point(field_get:Protocol.Vector3.z)
  return _internal_z();
}
inline void Vector3::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Vector3::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Protocol.Vector3.z)
}

// -------------------------------------------------------------------

// Rotator3

// float pitch = 1;
inline void Rotator3::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float Rotator3::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float Rotator3::pitch() const {
  // @@protoc_insertion_point(field_get:Protocol.Rotator3.pitch)
  return _internal_pitch();
}
inline void Rotator3::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void Rotator3::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:Protocol.Rotator3.pitch)
}

// float roll = 2;
inline void Rotator3::clear_roll() {
  _impl_.roll_ = 0;
}
inline float Rotator3::_internal_roll() const {
  return _impl_.roll_;
}
inline float Rotator3::roll() const {
  // @@protoc_insertion_point(field_get:Protocol.Rotator3.roll)
  return _internal_roll();
}
inline void Rotator3::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void Rotator3::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:Protocol.Rotator3.roll)
}

// float yaw = 3;
inline void Rotator3::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float Rotator3::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float Rotator3::yaw() const {
  // @@protoc_insertion_point(field_get:Protocol.Rotator3.yaw)
  return _internal_yaw();
}
inline void Rotator3::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void Rotator3::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Protocol.Rotator3.yaw)
}

// -------------------------------------------------------------------

// PlayerInfo

// uint64 playerId = 1;
inline void PlayerInfo::clear_playerid() {
  _impl_.playerid_ = uint64_t{0u};
}
inline uint64_t PlayerInfo::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint64_t PlayerInfo::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.playerId)
  return _internal_playerid();
}
inline void PlayerInfo::_internal_set_playerid(uint64_t value) {
  
  _impl_.playerid_ = value;
}
inline void PlayerInfo::set_playerid(uint64_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.playerId)
}

// .Protocol.ClassType playerClass = 2;
inline void PlayerInfo::clear_playerclass() {
  _impl_.playerclass_ = 0;
}
inline ::Protocol::ClassType PlayerInfo::_internal_playerclass() const {
  return static_cast< ::Protocol::ClassType >(_impl_.playerclass_);
}
inline ::Protocol::ClassType PlayerInfo::playerclass() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerInfo.playerClass)
  return _internal_playerclass();
}
inline void PlayerInfo::_internal_set_playerclass(::Protocol::ClassType value) {
  
  _impl_.playerclass_ = value;
}
inline void PlayerInfo::set_playerclass(::Protocol::ClassType value) {
  _internal_set_playerclass(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerInfo.playerClass)
}

// -------------------------------------------------------------------

// PlayerState

// uint64 playerId = 1;
inline void PlayerState::clear_playerid() {
  _impl_.playerid_ = uint64_t{0u};
}
inline uint64_t PlayerState::_internal_playerid() const {
  return _impl_.playerid_;
}
inline uint64_t PlayerState::playerid() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerState.playerId)
  return _internal_playerid();
}
inline void PlayerState::_internal_set_playerid(uint64_t value) {
  
  _impl_.playerid_ = value;
}
inline void PlayerState::set_playerid(uint64_t value) {
  _internal_set_playerid(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerState.playerId)
}

// .Protocol.ClassType playerClass = 2;
inline void PlayerState::clear_playerclass() {
  _impl_.playerclass_ = 0;
}
inline ::Protocol::ClassType PlayerState::_internal_playerclass() const {
  return static_cast< ::Protocol::ClassType >(_impl_.playerclass_);
}
inline ::Protocol::ClassType PlayerState::playerclass() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerState.playerClass)
  return _internal_playerclass();
}
inline void PlayerState::_internal_set_playerclass(::Protocol::ClassType value) {
  
  _impl_.playerclass_ = value;
}
inline void PlayerState::set_playerclass(::Protocol::ClassType value) {
  _internal_set_playerclass(value);
  // @@protoc_insertion_point(field_set:Protocol.PlayerState.playerClass)
}

// .Protocol.Vector3 playerLocation = 3;
inline bool PlayerState::_internal_has_playerlocation() const {
  return this != internal_default_instance() && _impl_.playerlocation_ != nullptr;
}
inline bool PlayerState::has_playerlocation() const {
  return _internal_has_playerlocation();
}
inline void PlayerState::clear_playerlocation() {
  if (GetArenaForAllocation() == nullptr && _impl_.playerlocation_ != nullptr) {
    delete _impl_.playerlocation_;
  }
  _impl_.playerlocation_ = nullptr;
}
inline const ::Protocol::Vector3& PlayerState::_internal_playerlocation() const {
  const ::Protocol::Vector3* p = _impl_.playerlocation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Vector3&>(
      ::Protocol::_Vector3_default_instance_);
}
inline const ::Protocol::Vector3& PlayerState::playerlocation() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerState.playerLocation)
  return _internal_playerlocation();
}
inline void PlayerState::unsafe_arena_set_allocated_playerlocation(
    ::Protocol::Vector3* playerlocation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.playerlocation_);
  }
  _impl_.playerlocation_ = playerlocation;
  if (playerlocation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.PlayerState.playerLocation)
}
inline ::Protocol::Vector3* PlayerState::release_playerlocation() {
  
  ::Protocol::Vector3* temp = _impl_.playerlocation_;
  _impl_.playerlocation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Vector3* PlayerState::unsafe_arena_release_playerlocation() {
  // @@protoc_insertion_point(field_release:Protocol.PlayerState.playerLocation)
  
  ::Protocol::Vector3* temp = _impl_.playerlocation_;
  _impl_.playerlocation_ = nullptr;
  return temp;
}
inline ::Protocol::Vector3* PlayerState::_internal_mutable_playerlocation() {
  
  if (_impl_.playerlocation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Vector3>(GetArenaForAllocation());
    _impl_.playerlocation_ = p;
  }
  return _impl_.playerlocation_;
}
inline ::Protocol::Vector3* PlayerState::mutable_playerlocation() {
  ::Protocol::Vector3* _msg = _internal_mutable_playerlocation();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerState.playerLocation)
  return _msg;
}
inline void PlayerState::set_allocated_playerlocation(::Protocol::Vector3* playerlocation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.playerlocation_;
  }
  if (playerlocation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(playerlocation);
    if (message_arena != submessage_arena) {
      playerlocation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, playerlocation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.playerlocation_ = playerlocation;
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerState.playerLocation)
}

// .Protocol.Rotator3 playerRotation = 4;
inline bool PlayerState::_internal_has_playerrotation() const {
  return this != internal_default_instance() && _impl_.playerrotation_ != nullptr;
}
inline bool PlayerState::has_playerrotation() const {
  return _internal_has_playerrotation();
}
inline void PlayerState::clear_playerrotation() {
  if (GetArenaForAllocation() == nullptr && _impl_.playerrotation_ != nullptr) {
    delete _impl_.playerrotation_;
  }
  _impl_.playerrotation_ = nullptr;
}
inline const ::Protocol::Rotator3& PlayerState::_internal_playerrotation() const {
  const ::Protocol::Rotator3* p = _impl_.playerrotation_;
  return p != nullptr ? *p : reinterpret_cast<const ::Protocol::Rotator3&>(
      ::Protocol::_Rotator3_default_instance_);
}
inline const ::Protocol::Rotator3& PlayerState::playerrotation() const {
  // @@protoc_insertion_point(field_get:Protocol.PlayerState.playerRotation)
  return _internal_playerrotation();
}
inline void PlayerState::unsafe_arena_set_allocated_playerrotation(
    ::Protocol::Rotator3* playerrotation) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.playerrotation_);
  }
  _impl_.playerrotation_ = playerrotation;
  if (playerrotation) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:Protocol.PlayerState.playerRotation)
}
inline ::Protocol::Rotator3* PlayerState::release_playerrotation() {
  
  ::Protocol::Rotator3* temp = _impl_.playerrotation_;
  _impl_.playerrotation_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::Protocol::Rotator3* PlayerState::unsafe_arena_release_playerrotation() {
  // @@protoc_insertion_point(field_release:Protocol.PlayerState.playerRotation)
  
  ::Protocol::Rotator3* temp = _impl_.playerrotation_;
  _impl_.playerrotation_ = nullptr;
  return temp;
}
inline ::Protocol::Rotator3* PlayerState::_internal_mutable_playerrotation() {
  
  if (_impl_.playerrotation_ == nullptr) {
    auto* p = CreateMaybeMessage<::Protocol::Rotator3>(GetArenaForAllocation());
    _impl_.playerrotation_ = p;
  }
  return _impl_.playerrotation_;
}
inline ::Protocol::Rotator3* PlayerState::mutable_playerrotation() {
  ::Protocol::Rotator3* _msg = _internal_mutable_playerrotation();
  // @@protoc_insertion_point(field_mutable:Protocol.PlayerState.playerRotation)
  return _msg;
}
inline void PlayerState::set_allocated_playerrotation(::Protocol::Rotator3* playerrotation) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.playerrotation_;
  }
  if (playerrotation) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(playerrotation);
    if (message_arena != submessage_arena) {
      playerrotation = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, playerrotation, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.playerrotation_ = playerrotation;
  // @@protoc_insertion_point(field_set_allocated:Protocol.PlayerState.playerRotation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
