;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Glide",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.StopGlide",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Combat",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Gliding",DevComment="")
+GameplayTagList=(Tag="State.Jumping",DevComment="")

