;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Glide",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.Teleport",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.CloseAttack",DevComment="")
+GameplayTagList=(Tag="Ability.StopGlide",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB3",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.Teleport",DevComment="")
+GameplayTagList=(Tag="Data",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit",DevComment="")
+GameplayTagList=(Tag="Faction.Asmodian",DevComment="")
+GameplayTagList=(Tag="Faction.Elyos",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.RB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.LB",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.CloseAttack",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Combat",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Gliding",DevComment="")
+GameplayTagList=(Tag="State.Jumping",DevComment="")
+GameplayTagList=(Tag="State.Sprint",DevComment="")
+GameplayTagList=(Tag="Team.Daeva",DevComment="")
+GameplayTagList=(Tag="Team.Monster",DevComment="")

