;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="GameplayCue.Hit.Ranger.Key#",NewTagName="GameplayCue.Hit.Ranger.KeyE")
+GameplayTagList=(Tag="Ability.Attack",DevComment="")
+GameplayTagList=(Tag="Ability.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Glide",DevComment="")
+GameplayTagList=(Tag="Ability.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.ST.PT1",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.CloseAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.Dead",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.MELEEAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Ability.StopGlide",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.LB3",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB2",DevComment="")
+GameplayTagList=(Tag="Combo.Available.RB3",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Cooldown.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Data",DevComment="")
+GameplayTagList=(Tag="Data.AttackSlowDuration",DevComment="")
+GameplayTagList=(Tag="Data.Cooldown.Duration",DevComment="")
+GameplayTagList=(Tag="Data.Damage",DevComment="")
+GameplayTagList=(Tag="Data.HitManaRegen",DevComment="")
+GameplayTagList=(Tag="Data.ManaCost",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit.Begin",DevComment="")
+GameplayTagList=(Tag="Event.CheckAttackHit.End",DevComment="")
+GameplayTagList=(Tag="Faction.Asmodian",DevComment="")
+GameplayTagList=(Tag="Faction.Elyos",DevComment="")
+GameplayTagList=(Tag="GameplayCue.GhostTrail",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key3",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.Key4",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.KeyE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Assassin.RB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key1",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key2",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key3",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.Key4",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.KeyE",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Ranger.RB",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key1",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key2",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key3",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.Key4",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.KeyE",DevComment="")
+GameplayTagList=(Tag="GamePlayCue.Hit.Templar.KeyQ",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Templar.LB",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Hit.Templar.RB",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator",DevComment="")
+GameplayTagList=(Tag="Montage.Siliator.PT1",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.CloseAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.Dead",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.RangedAttack",DevComment="")
+GameplayTagList=(Tag="Montage.Talythra.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Combat",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.Dead",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.OutofCombat",DevComment="")
+GameplayTagList=(Tag="Phase.Monster.PreCombat",DevComment="")
+GameplayTagList=(Tag="State.Attacking",DevComment="")
+GameplayTagList=(Tag="State.Combat",DevComment="")
+GameplayTagList=(Tag="State.Dashing",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.Gliding",DevComment="")
+GameplayTagList=(Tag="State.Jumping",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.ChargeAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Chase",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Dead",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.Idle",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.MeleeAttack",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.RangedShot",DevComment="")
+GameplayTagList=(Tag="State.Monster.TH.TeleportAttack",DevComment="")
+GameplayTagList=(Tag="State.Sprint",DevComment="")
+GameplayTagList=(Tag="Team.Daeva",DevComment="")
+GameplayTagList=(Tag="Team.Monster",DevComment="")

