// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Enum.proto
// Protobuf C++ Version: 6.33.4

#ifndef Enum_2eproto_2epb_2eh
#define Enum_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_Enum_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_Enum_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_Enum_2eproto;
}  // extern "C"
namespace Protocol {
enum EClassType : int;
extern const uint32_t EClassType_internal_data_[];
}  // namespace Protocol
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::Protocol::EClassType_internal_data_>
    internal::EnumTraitsImpl::value<::Protocol::EClassType>;
}  // namespace protobuf
}  // namespace google

namespace Protocol {
enum EClassType : int {
  CLASS_NONE = 0,
  ASSASSIN = 1,
  CLERIC = 2,
  RANGER = 3,
  TEMPLAR = 4,
  EClassType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  EClassType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t EClassType_internal_data_[];
inline constexpr EClassType EClassType_MIN =
    static_cast<EClassType>(0);
inline constexpr EClassType EClassType_MAX =
    static_cast<EClassType>(4);
inline bool EClassType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
inline constexpr int EClassType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EClassType_descriptor();
template <typename T>
const ::std::string& EClassType_Name(T value) {
  static_assert(::std::is_same<T, EClassType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EClassType_Name().");
  return EClassType_Name(static_cast<EClassType>(value));
}
template <>
inline const ::std::string& EClassType_Name(EClassType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EClassType_descriptor, 0, 4>(
      static_cast<int>(value));
}
inline bool EClassType_Parse(
    ::absl::string_view name, EClassType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EClassType>(EClassType_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::Protocol::EClassType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::Protocol::EClassType>() {
  return ::Protocol::EClassType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // Enum_2eproto_2epb_2eh
